name: bitcoindart
description: A dart Bitcoin library for Flutter. BIP32, BIP39, P2PKH integration.
version: 2.2.1
homepage: https://github.com/keybagio/bitcoindart
author: KY <harrykyguo@gmail.com>

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  bip39: ^1.0.3
  bip32: ^1.0.5
  pointycastle: ^3.3.2
  hex: ^0.2.0
  bs58check: ^1.0.2
  meta: ^1.2.3
  bech32: ^0.2.1
  
dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.9.0
